POST http://localhost:5000/api/poll/new HTTP/1.1
Content-Type: application/json

{
	"title": "What's better, React or Vue?",
	"options": [
		"React",
		"Vue"
	] 
}

###

POST http://localhost:5000/api/poll/toggle-active HTTP/1.1
Content-Type: application/json

{
	"id": "62698e399011ccd631b07baf"
}

###

GET http://localhost:5000/api/poll/results/62698e399011ccd631b07baf HTTP/1.1

###

GET http://localhost:5000/api/poll/active HTTP/1.1