POST http://localhost:5000/api/poll/new HTTP/1.1
Content-Type: application/json

{
	"title": "What's the better framework?",
	"options": [
		"React",
		"Vue",
		"Angular",
		"Svelte"
	] 
}

###

POST http://localhost:5000/api/poll/toggle-active HTTP/1.1
Content-Type: application/json

{
	"id": "626a888afd7fbad237c64811"
}

###

GET http://localhost:5000/api/poll/results HTTP/1.1

###

GET http://localhost:5000/api/poll/active HTTP/1.1

###

POST http://localhost:5000/api/poll/vote HTTP/1.1
Content-Type: application/json

{
	"id": "626a888afd7fbad237c64811",
	"option": 1
}