POST http://localhost:3000/api/poll/new HTTP/1.1
Content-Type: application/json

{
	"title": "What's better, React or Vue?",
	"options": [
		"React",
		"Vue"
	] 
}

###

POST http://localhost:5000/api/poll/toggle-active HTTP/1.1
Content-Type: application/json

{
	"id": "6269397be2e7cc7962e4b7f0"
}

###

GET http://localhost:3000/api/poll/results/6269397be2e7cc7962e4b7f0 HTTP/1.1